export const GAME_CONFIG = {
  DEFAULT_TIME_LIMIT: 120, // 2 minutes in seconds
  DEFAULT_TARGET_BATS: 25,
  MAX_BATS_ON_SCREEN: 8,
  COLORS: { PRIMARY: '#9F33FF', SECONDARY: '#FF3366', BACKGROUND: '#1A0026', TEXT: '#FFFFFF' },
  POINTS_PER_BAT: 100,
  STAMINA_COST_PER_SHOT: 5,
  STAMINA_REGEN_RATE: 1, // Points per second
  DIFFICULTY_LEVELS: {
    EASY: { BAT_SPEED: 0.3, SPAWN_RATE: 3000, MAX_BATS: 5 },
    MEDIUM: { BAT_SPEED: 0.5, SPAWN_RATE: 2000, MAX_BATS: 8 },
    HARD: { BAT_SPEED: 0.8, SPAWN_RATE: 1500, MAX_BATS: 12 }
  },
  CURRENT_DIFFICULTY: 'MEDIUM',
  SOUND_ENABLED: true
};
